### ISSUE TITLE
Data citations

### ISSUE THREAD

**Issue by dnoesgaard** [TarekHattab/SDM#1]
Hi there, this is Daniel from GBIF. I came across your scripts in your recent paper in Ecological Informatics.

When using data from GBIF and publishing results in a paper, the GBIF user agreement requires that you acknowledge the specific data publishers whose data you've used. As far as I can tell, your script strips the occurrence records of identifiers in an early step, which of course makes this a bit hard.

A solution could be either to use the rgbif occ_download() method because this generates a unique DOI for easy citation. Or, you could use the citation helper from the same package—gbif_citation()—to loop through the records and generate the necessary citations, e.g.

```
> occOther <- occ(query=as.character("Mullus surmuletus"),
+                 from=c("gbif"),
+                 has_coords = T,limit = 100000)
> gbif_citation(occ2df(occOther)$key[1])$citation$citation
[1] "Ueda K (2020). iNaturalist Research-grade Observations. iNaturalist.org. Occurrence dataset https://doi.org/10.15468/ab3s5x accessed via GBIF.org on 2020-07-24.. Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2020-07-24"
```

Let me know if you have any questions or thoughts on this!

**Comment by TarekHattab** [comment]
Hi Daniel, Thank you very much for your suggestion, I added a line (166) to extract DOI. 
Best, 
Tarek
